### PR TITLE
not able to use obstacle list 

### PR DESCRIPTION
**Pull request by mnottheone**
I and daivik did this , now need to get obstacles list so we can polpulate the graph.

Right now we are using manually generated obstacle list.

Add code so that we can use simulator's obstacle list for getting obstacles position and dimension

### CODE REVIEW

**Comment by sam17** [comment]
Are you not getting obstacle list? I think its being published already. See
the readme of this repo.

**Comment by mnottheone** [comment]
on running echo command , getting
 " WARNING: topic [/obstacleList] does not appear to be published yet"
we just want to know how to use it ?

**Comment by sam17** [comment]
Did you run the other roslaunch?

**Comment by mnottheone** [comment]
okay , I think I got it . Now we need to write a subscriber for obstaclelist in our get path file.

**Comment by sam17** [comment]
Yea.

**Pull request closed without merging**
